eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/


---
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/rksharma1401/spring-config # default 
          search-paths:
            - 'userApp*'
  

