---
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/rksharma1401/spring-config # default 
          search-paths:
            - 'userApp*'
eureka:
      client:
        register-with-eureka: false
        fetch-registry: false