---
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/rksharma1401/spring-config # default 
          search-paths:
            - 'userApp*'
  

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://spring-conf-server.herokuapp.com/eureka/ 